
base:
  gpu_id: ['0', '1']
  loss_name: 'weighted_binary_cross_entropy'
  scheduler_name: 'warmup_scheduler'
  opt_name: 'adam'
data:
  dataset_name: 'adj_dataset'
  image_size: 512
  crop_width: 512
  fold: 2
  is_train: True
  is_std: False
  is_multi_channel: &is_multi_channel False
  window_aug: True
  window_policy: 2
  use_smooth_label: False
model:
  model_name: 'densenet'
  classes: 6
  is_pretrained: True
  is_window: False
  branch_head: False
  is_multi_channel: *is_multi_channel
  adj_model: True
train:
  seed: 7777
  batch_size: 16
  epoch: 3
  learning_rate: 0.00001
  accumulation_steps: 1
  warm_start: False
test:
  batch_size: 32
  is_validation: False
  is_tta: True
save:
  save_path: ./intermediate_output/densenet_adj_prediction
  description: 512x512 image, densenet, binary_cross_entropy, img_{i-1} img_{i} img_{i+1} for input